@baseUrl=localhost:3524/api/fflags

### Creates a new flag
POST http://{{baseUrl}} HTTP/1.1
Content-Type: application/json

< ./fflagTwo.json
### id: 6716b23a14d303db95a4f94f
### ABTest => id : 671949c5fa3bd465b5781038

### finalFlag = id : 6719f88df5073d30f55be3a4

### Updates flag using its id
PUT http://{{baseUrl}}/648d2d5c14ca747a5c10dc84
Content-Type: application/json

{
  "id": "648d2d5c14ca747a5c10dc84",
  "name": "flagOne",
  "description": "flagOne",
  "environments": {
    "staging": {
      "userGroups": {
        "newFeatureAccess": {
          "enabled": true,
          "value": 200
        },
        "oldFeatureAccess": {
          "enabled": false,
          "value": 300
        }
      }
    },
    "production": {
      "userGroups": {
        "newFeatureAccess": {
          "enabled": false,
          "value": 400
        },
        "oldFeatureAccess": {
          "enabled": true,
          "value": 500
        }
      }
    }
  }
}

### Physically deletes flag using its id
DELETE http://{{baseUrl}}/648d2d5c14ca747a5c10dc84
Accept: text/json

> {%
    client.test("DELETE executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Returns flag by its id
GET http://{{baseUrl}}/6716b23a14d303db95a4f94f
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.body.hasOwnProperty("name"), "Body does not have the field name");
        client.assert(response.body["name"] === "flagOne");
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Returns all flags for caching
GET http://{{baseUrl}}/caching/testing
Accept: application/json